AspNetMvcBlog/Models/ErrorViewModel.cs
namespace AspNetMvcBlog.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AspNetMvcBlog/Areas/Admin/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetMvcBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BlogController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AspNetMvcBlog/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetMvcBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AspNetMvcBlog/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetMvcBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AspNetMvcBlog/Areas/Admin/Controllers/PageController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetMvcBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PageController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AspNetMvcBlog/Areas/Admin/Controllers/SettingController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetMvcBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SettingController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AspNetMvcBlog/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetMvcBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AspNetMvcBlog/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetMvcBlog.Controllers
{
    public class AuthController : Controller
    {
        public IActionResult Register()
        {
            return View();
        }
        public IActionResult Login()
        {
            return View();
        }
        public IActionResult ForgotPassword()
        {
            return View();
        }

    }
}

AspNetMvcBlog/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetMvcBlog.Controllers
{
    public class BlogController : Controller
    {
        public IActionResult Search(string query)
        {
            return View();
        }
        public IActionResult Detail(int id)
        {
            return View();
        }

    }
}

AspNetMvcBlog/Controllers/CategoryController.cs
using AspNetMvcBlog.Data;
using Microsoft.AspNetCore.Mvc;


namespace AspNetMvcBlog.Controllers
{
    public class CategoryController : Controller
    {
        public IActionResult Index(int cid)
        {
            return View();
        }
      

    }
}

AspNetMvcBlog/Controllers/HomeController.cs
using AspNetMvcBlog.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AspNetMvcBlog.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Category()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AspNetMvcBlog/Controllers/PageController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetMvcBlog.Controllers
{
    public class PageController : Controller
    {
        public IActionResult Detail(int id)
        {
            return View();
        }
    }
}

AspNetMvcBlog/Controllers/SearchController.cs
using AspNetMvcBlog.Data;
using Microsoft.AspNetCore.Mvc;

namespace AspNetMvcBlog.Controllers
{
    public class SearchController : Controller
    {
        private readonly AppDbContext db;

        public SearchController(AppDbContext db)
        {
            this.db = db;
        }
        
        [HttpPost]
        public IActionResult Index(string q)
        {
            var searchList = db.Posts.Where(x => x.Title == q || x.Content == q).ToList();
            return View(searchList);
        }

    }
}

AspNetMvcBlog/Areas/Admin/Views/Category/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

AspNetMvcBlog/Areas/Admin/Views/Home/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

AspNetMvcBlog/Areas/Admin/Views/Page/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

AspNetMvcBlog/Areas/Admin/Views/Setting/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

AspNetMvcBlog/Areas/Admin/Views/User/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

AspNetMvcBlog/Views/Home/Index.cshtml
<partial name="~/Views/Shared/_HeaderPartialView.cshtml" />
<partial name="~/Views/Shared/_SliderPartialView.cshtml" />
<partial name="~/Views/Shared/_ArticlePartialView.cshtml" />

<section class="footer-2 section-padding gray-bg pb-5">
    <div class="container">
        <partial name="~/Views/Shared/_SubscribePartialView.cshtml" />
        <partial name="~/Views/Shared/_FooterPartialView.cshtml" />
    </div>
</section>

AspNetMvcBlog/Views/Page/Detail.cshtml
@{
    ViewBag.Title="Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<partial name="~/Views/Shared/_HeaderPartialView.cshtml" />
<partial name="~/Views/Shared/_SearchPartialView.cshtml" />
<partial name="~/Views/Shared/_FooterPartial2View.cshtml" />
<partial name="~/Views/Shared/_SectionPartialView.cshtml" />

AspNetMvcBlog/Views/Search/Index.cshtml
@using AspNetMvcBlog.Data.Models
@model List<Post>

 @foreach(var item in Model){
     <h1>
         @item.Title

     </h1>
     <p> @item.Content </p>
 }

AspNetMvcBlog/Views/Shared/_ArticlePartialView.cshtml
	<section class="section-padding">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="row">
						<div class="col-lg-3 col-md-6">
							<article class="post-grid mb-5">
								<a class="post-thumb mb-4 d-block" href="blog-single.html">
									<img src="images/news/f1.jpg" alt="" class="img-fluid w-100">
								</a>
								<span class="cat-name text-color font-extra text-sm text-uppercase letter-spacing-1">Explore</span>
								<h3 class="post-title mt-1"><a href="blog-single.html">The best place to explore to enjoy</a></h3>
								<span class="text-muted letter-spacing text-uppercase font-sm">June 15, 2019</span>
							</article>
						</div>
						<div class="col-lg-3 col-md-6">
							<article class="post-grid mb-5">
								<a class="post-thumb mb-4 d-block" href="blog-single.html">
									<img src="images/news/f2.jpg" alt="" class="img-fluid w-100">
								</a>
								<span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Lifestyle</span>
								<h3 class="post-title mt-1"><a href="blog-single.html">How to Make list for travelling alone</a></h3>
								<span class="text-muted letter-spacing text-uppercase font-sm">September 15, 2019</span>
							</article>
						</div>
						<div class="col-lg-3 col-md-6">
							<article class="post-grid mb-5">
								<a class="post-thumb mb-4 d-block" href="blog-single.html">
									<img src="images/news/f3.jpg" alt="" class="img-fluid w-100">
								</a>
								<span class=" cat-name text-color font-sm font-extra text-uppercase letter-spacing">Food</span>
								<h3 class="post-title mt-1"><a href="blog-single.html">5 ingredient cilantro vinaigrette</a></h3>
								<span class="text-muted letter-spacing text-uppercase font-sm">September 15, 2019</span>
							</article>
						</div>
						<div class="col-lg-3 col-md-6">
							<article class="post-grid mb-5">
								<a class="post-thumb mb-4 d-block" href="blog-single.html">
									<img src="images/news/f4.jpg" alt="" class="img-fluid w-100">
								</a>
								<span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Explore</span>
								<h3 class="post-title mt-1"><a href="blog-single.html">A Simple Way to Feel Like Home When You Travel</a></h3>
								<span class="text-muted letter-spacing text-uppercase font-sm">March 20, 2019</span>
							</article>
						</div>
						<div class="col-lg-3 col-md-6">
							<article class="post-grid mb-5">
								<a class="post-thumb mb-4 d-block" href="blog-single.html">
									<img src="images/news/f5.jpg" alt="" class="img-fluid w-100">
								</a>
								<span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Travel</span>
								<h3 class="post-title mt-1"><a href="blog-single.html">What Type of Traveller Are You?</a></h3>
								<span class="text-muted letter-spacing text-uppercase font-sm">September 15, 2019</span>
							</article>
						</div>
						<div class="col-lg-3 col-md-6">
							<article class="post-grid mb-5">
								<a class="post-thumb mb-4 d-block" href="blog-single.html">
									<img src="images/news/f6.jpg" alt="" class="img-fluid w-100">
								</a>
								<span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Experience</span>
								<h3 class="post-title mt-1"><a href="blog-single.html">A Road Trip Review of the 2018</a></h3>
								<span class="text-muted letter-spacing text-uppercase font-sm">July 10, 2019</span>
							</article>
						</div>
						<div class="col-lg-3 col-md-6">
							<article class="post-grid mb-5">
								<a class="post-thumb mb-4 d-block" href="blog-single.html">
									<img src="images/news/f7.jpg" alt="" class="img-fluid w-100">
								</a>
								<span class=" cat-name text-color font-sm font-extra text-uppercase letter-spacing">music</span>
								<h3 class="post-title mt-1"><a href="blog-single.html">Portugal’s Sunset summer vission</a></h3>
								<span class="text-muted letter-spacing text-uppercase font-sm">September 15, 2019</span>
							</article>
						</div>
						<div class="col-lg-3 col-md-6">
							<article class="post-grid mb-5">
								<a class="post-thumb mb-4 d-block" href="blog-single.html">
									<img src="images/news/f8.jpg" alt="" class="img-fluid w-100">
								</a>
								<span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">beauty</span>
								<h3 class="post-title mt-1"><a href="blog-single.html">The best soft Tropical Getaway</a></h3>
								<span class="text-muted letter-spacing text-uppercase font-sm">March 12, 2019</span>
							</article>
						</div>
						<div class="col-lg-3 col-md-6">
							<article class="post-grid mb-5">
								<a class="post-thumb mb-4 d-block" href="blog-single.html">
									<img src="images/news/f9.jpg" alt="" class="img-fluid w-100">
								</a>
								<span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Travel</span>
								<h3 class="post-title mt-1"><a href="blog-single.html">Memoriable Paris Girls Trip </a></h3>
								<span class="text-muted letter-spacing text-uppercase font-sm">April 19, 2019</span>
							</article>
						</div>
						<div class="col-lg-3 col-md-6">
							<article class="post-grid mb-5">
								<a class="post-thumb mb-4 d-block" href="blog-single.html">
									<img src="images/news/f10.jpg" alt="" class="img-fluid w-100">
								</a>
								<span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Experience</span>
								<h3 class="post-title mt-1"><a href="blog-single.html">How to Plan your Trip the Right Way</a></h3>
								<span class="text-muted letter-spacing text-uppercase font-sm">February 15, 2019</span>
							</article>
						</div>
						<div class="col-lg-3 col-md-6">
							<article class="post-grid mb-5">
								<a class="post-thumb mb-4 d-block" href="blog-single.html">
									<img src="images/news/f11.jpg" alt="" class="img-fluid w-100">
								</a>
								<span class="cat-name text-color font-sm font-extra text-uppercase letter-spacing">Travel</span>
								<h3 class="post-title mt-1"><a href="blog-single.html">8 Powerful Ways to Add Vibrant Colour to Your Life</a></h3>
								<span class="text-muted letter-spacing text-uppercase font-sm">August 15, 2019</span>
							</article>
						</div>
						<div class="col-lg-3 col-md-6">
							<article class="post-grid mb-5">
								<a class="post-thumb mb-4 d-block" href="blog-single.html">
									<img src="images/news/f12.jpg" alt="" class="img-fluid w-100">
								</a>
								<span class=" cat-name text-color font-sm font-extra text-uppercase letter-spacing">Lifestyle</span>
								<h3 class="post-title mt-1"><a href="blog-single.html">The best to-do list to help boost your productivity</a></h3>
								<span class="text-muted letter-spacing text-uppercase font-sm">October 2, 2019</span>
							</article>
						</div>
					</div>
				</div>
				<div class="m-auto">
					<div class="pagination mt-5 pt-4">
						<ul class="list-inline ">
							<li class="list-inline-item"><a href="#" class="active">1</a></li>
							<li class="list-inline-item"><a href="#">2</a></li>
							<li class="list-inline-item"><a href="#">3</a></li>
							<li class="list-inline-item"><a href="#" class="prev-posts"><i class="ti-arrow-right"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</section>

AspNetMvcBlog/Views/Shared/_FooterPartial2View.cshtml
<footer class="footer-section bg-grey">
		<div class="instagram-photo-section">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<h4 class="text-center">Follow in Instagram</h4>
					</div>
				</div>

				<div class="row no-gutters" id="instafeed">

				</div>
			</div>
		</div>
		</div>

		<div class="container">
			<div class="row">
				<div class="col-lg-12 text-center">
					<div class="mb-4">
						<h2 class="footer-logo">Revolve.</h2>
					</div>
					<ul class="list-inline footer-socials">
						<li class="list-inline-item"><a href="#"><i class="ti-facebook mr-2"></i>Facebook</a></li>
						<li class="list-inline-item"><a href="#"><i class="ti-twitter mr-2"></i>Twitter</a></li>
						<li class="list-inline-item"><a href="#"><i class="ti-linkedin mr-2"></i>Linkedin</a></li>
						<li class="list-inline-item"><a href="#"><i class="ti-pinterest mr-2"></i>Pinterest</a></li>
						<li class="list-inline-item"><a href="#"><i class="ti-github mr-2"></i>Github</a></li>
						<li class="list-inline-item"><a href="#"><i class="ti-instagram mr-2"></i>Instrgram</a></li>
						<li class="list-inline-item"><a href="#"><i class="ti-rss mr-2"></i>rss</a></li>
					</ul>
				</div>

				<div class="col-md-12 text-center">
					<p class="copyright">© Copyright 2019 - Revolve. All Rights Reserved.</p>
				</div>
			</div>
		</div>
	</footer>

AspNetMvcBlog/Views/Shared/_FooterPartialView.cshtml
<div class="footer-btm mt-5 pt-4 border-top">
	<div class="row">
		<div class="col-lg-12">
			<ul class="list-inline footer-socials-2 text-center">
				<li class="list-inline-item"><a href="#">Privacy policy</a></li>
				<li class="list-inline-item"><a href="#">Support</a></li>
				<li class="list-inline-item"><a href="#">About</a></li>
				<li class="list-inline-item"><a href="#">Contact</a></li>
				<li class="list-inline-item"><a href="#">Terms</a></li>
				<li class="list-inline-item"><a href="#">Category</a></li>
			</ul>
		</div>
	</div>
	<div class="row justify-content-center">
		<div class="col-lg-6">
			<div class="copyright text-center ">
				Copyright © <a href="#">AspNetMvcBlog</a> - @DateTime.Now.Year
			</div>
		</div>
	</div>
</div>

AspNetMvcBlog/Views/Shared/_HeaderPartialView.cshtml
<header class="header-top bg-grey justify-content-center">
	<div class="container">
		<div class="row align-items-center">
			<div class="col-lg-2 col-md-4 text-center d-none d-lg-block">
				<a class="navbar-brand" asp-controller="Home" asp-action="Index">
					<img src="~/images/logo.png" alt="" class="img-fluid" />
				</a>
			</div>
			<div class="col-lg-8 col-md-12">
				<nav class="navbar navbar-expand-lg navigation-2 navigation">
					<a class="navbar-brand text-uppercase d-lg-none" asp-controller="Home" asp-action="Index">
						<img src="~/images/logo.png" alt="" class="img-fluid">
					</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
						<span class="ti-menu"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbar-collapse">
						<ul id="menu" class="menu navbar-nav mx-auto">
							<li class="nav-item"><a  asp-controller="Home" asp-action="Index" class="nav-link">Home</a></li>
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									Blog Posts
								</a>
								<div class="dropdown-menu" aria-labelledby="navbarDropdown2">
									<a class="dropdown-item" href="standard-fullwidth.html">Standard Fullwidth</a>
									<a class="dropdown-item" href="standard-left-sidebar.html">Standard Left Sidebar</a>
									<a class="dropdown-item" href="standard-right-sidebar.html">Standard Right Sidebar</a>
								</div>
							</li>
							<li class="nav-item"><a href="about.html" class="nav-link">About</a></li>
							<li class="nav-item"><a asp-controller="Category" asp-action="Index" class="nav-link">Category</a></li>
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown3" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									Post Format
								</a>
								<div class="dropdown-menu" aria-labelledby="navbarDropdown3">
									<a class="dropdown-item" href="post-video.html">Video Formats</a>
									<a class="dropdown-item" href="post-audio.html">Audio Format</a>
									<a class="dropdown-item" href="post-link.html">Quote Format</a>
									<a class="dropdown-item" href="post-gallery.html">Gallery Format</a>
									<a class="dropdown-item" href="post-image.html">Image Format</a>
								</div>
							</li>
							<li class="nav-item"><a href="contact.html" class="nav-link">Contact</a></li>
						</ul>
						<ul class="list-inline mb-0 d-block d-lg-none">
							<li class="list-inline-item"><a href="#"><i class="ti-facebook"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="ti-twitter"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="ti-linkedin"></i></a></li>
							<li class="list-inline-item"><a href="#"><i class="ti-pinterest"></i></a></li>
						</ul>
					</div>
				</nav>
			</div>
			<div class="col-lg-2 col-md-4 col-6">
				<div class="header-socials-2 text-right d-none d-lg-block">
					<ul class="list-inline mb-0">
						<li class="list-inline-item"><a href="#"><i class="ti-facebook"></i></a></li>
						<li class="list-inline-item"><a href="#"><i class="ti-twitter"></i></a></li>
						<li class="list-inline-item"><a href="#"><i class="ti-linkedin"></i></a></li>
						<li class="list-inline-item"><a href="#"><i class="ti-pinterest"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>

<div class="row">
    <div class="col-md-5">
        <form asp-controller="Search" asp-action="Index" method="post" class="d-flex align-items-center">
            <input asp-controller="Search" asp-action="Index" type="text" name="q" class="form-control" value="q" placeholder="What are you looking for?" />
            <input type="submit" value="Search" class="btn btn-primary ms-2" />
        </form>
    </div>
</div>
</header>

AspNetMvcBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"] - Siliconmade Personel Blog</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!--Favicon-->
    <link rel="shortcut icon" href="~/images/favicon.ico" type="image/x-icon">

    <!-- THEME CSS
    ================================================== -->
    <!-- Bootstrap -->
    <link rel="stylesheet" href="~/plugins/bootstrap/css/bootstrap.min.css">
    <!-- Themify -->
    <link rel="stylesheet" href="~/plugins/themify/css/themify-icons.css">
    <link rel="stylesheet" href="~/plugins/slick-carousel/slick-theme.css">
    <link rel="stylesheet" href="~/plugins/slick-carousel/slick.css">
    <!-- Slick Carousel -->
    <link rel="stylesheet" href="~/plugins/owl-carousel/owl.carousel.min.css">
    <link rel="stylesheet" href="~/plugins/owl-carousel/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/plugins/magnific-popup/magnific-popup.css">
    <!-- manin stylesheet -->
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AspNetMvcBlog.styles.css" asp-append-version="true" />
</head>
<body>
    @RenderBody()

    <!-- THEME JAVASCRIPT FILES
    ================================================== -->
    <!-- initialize jQuery Library -->
    <script src="~/plugins/jquery/jquery.js"></script>
    <!-- Bootstrap jQuery -->
    <script src="~/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/plugins/bootstrap/js/popper.min.js"></script>
    <!-- Owl caeousel -->
    <script src="~/plugins/owl-carousel/owl.carousel.min.js"></script>
    <script src="~/plugins/slick-carousel/slick.min.js"></script>
    <script src="~/plugins/magnific-popup/magnific-popup.js"></script>
    <!-- Instagram Feed Js -->
    <script src="~/plugins/instafeed-js/instafeed.min.js"></script>
    <!-- Google Map -->
    @*<script src="~/maps/api/js_key_AIzaSyCC72vZw-6tGqFyRhhg5CkF2fqfILn2Tsw.js"></script>*@
    <script src="~/plugins/google-map/gmap.js"></script>
    <!-- main js -->
    <script src="~/js/custom.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AspNetMvcBlog/Views/Shared/_SearchPartialView.cshtml
	<div class="search-wrap">
		<div class="overlay">
			<form action="#" class="search-form">
				<div class="container">
					<div class="row">
						<div class="col-md-10 col-9">
							<input type="text" class="form-control" placeholder="Search..." />
						</div>
						<div class="col-md-2 col-3 text-right">
							<div class="search_toggle toggle-wrap d-inline-block">
								<i class="ti-close"></i>
							</div>
						</div>
					</div>
				</div>
			</form>
		</div>
	</div>

AspNetMvcBlog/Views/Shared/_SubscribePartialView.cshtml
<div class="row justify-content-center">
	<div class="col-lg-6">
		<div class="subscribe-footer text-center">
			<div class="form-group mb-0">
				<h2 class="mb-3">Subscribe Newsletter</h2>
				<p class="mb-4">Subscribe my Newsletter for new blog posts , tips and info.
				<p>
				<div class="form-group form-row align-items-center mb-0">
					<div class="col-sm-9">
						<input type="email" class="form-control" placeholder="Email Address">
					</div>
					<div class="col-sm-3">
						<a href="#" class="btn btn-dark ">Subscribe</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>